### ISSUE TITLE
daily-python not installable via pip

### ISSUE THREAD

**Issue by trzy** [daily-co/daily-python#16]
I am trying to to test Daily's fast voice agent demo (https://github.com/CerebriumAI/examples/tree/master/18-realtime-voice-agent) locally and am running into numerous issues:

1. In that project, `pipecat-ai[silero, daily, openai, deepgram]` is not something pip can install but `pipecat-ai` works fine.
2. However, the Daily package is still missing. `pip install daily-python` doesn't work.
3. Trying to clone `daily-python` locally doesn't work either because of dependencies on `daily-core`, etc.

Is there any way to get that demo running? Thank you.

**Comment by aconchillo** [comment]
By any chance, are you using Windows? If so, you will need to use WSL. I know it's not very convenient but that's the only way to run in Windows. If not, what platform are you using?

**Comment by trzy** [comment]
Ah yes, I am using Windows. I'll try it out on Mac. Would be nice to get native Windows support, though!
