### ISSUE TITLE
pip install daily-python is not work now

### ISSUE THREAD

**Issue by cqnimin** [daily-co/daily-python#17]
pip install daily-python is not work now

i tried the command as below:
pip install daily-python
pip install daily-python==0.10.1

error message as below

ERROR: Could not find a version that satisfies the requirement daily-python (from versions: none)

**Comment by aconchillo** [comment]
Hi! Are you using Windows by any chance? If so, right now the only way to use `daily-python` in WIndows is through WSL.

**Comment by cqnimin** [comment]
oh, yes, you are right. i am installing it on windows.thanks for your help

**Comment by aconchillo** [comment]
Closing, duplicate of #7
