### ISSUE TITLE
Is self._speaker.read_frames(...) blocking?

### ISSUE THREAD

**Issue by RevanthRameshkumar** [daily-co/daily-python#18]
Hello, is the read_frames function blocking? When I inspect it, I noticed there is a callback option but the function itself also returns bytes so I am assuming it is blocking?
If I want it to not block my threads/event loops should I call it inside an async function and then await that async function?

Thanks!

**Comment by aconchillo** [comment]
@RevanthRameshkumar Hi! Yes, `read_frames()` is blocking. If you want to use the non-blocking approach you should create the speaker device with `non_blocking=True` and then you can use futures. See this for an example: https://github.com/daily-co/daily-python/issues/3#issuecomment-2174442529

**Comment by RevanthRameshkumar** [comment]
Thanks! Looks like that is a new param? Seems like a good idea, looking forward to using it 👍
