### ISSUE TITLE
Can I mute a speaker mid stream?

### ISSUE THREAD

**Issue by RevanthRameshkumar** [daily-co/daily-python#20]
I used the daily python sdk to push out 10 seconds of audio from a queue on the server. Pushing the audio data to the microphone takes quite a bit shorter time than the participants in the call to actually hear all 10 seconds of that audio.
Is there a way I can stop the audio render from the server once I push it into daily?

**Comment by aconchillo** [comment]
Hi @RevanthRameshkumar ! In your code, when do you start sending audio?

**Comment by RevanthRameshkumar** [comment]
no worries on this, I resolved the issue by making everything async and waiting to send n+1 until n is complete
