### ISSUE TITLE
encounter connetion timeout

### ISSUE THREAD

**Issue by linyubupa** [daily-co/daily-python#21]
##here is the code
from daily import *
from PIL import Image
from openai import OpenAI
import argparse
import io
import os
import time
import wave
from base64 import b64decode

Daily.init()

CAMERA_WIDTH = 1024
CAMERA_HEIGHT = 1024

speaker = Daily.create_speaker_device(
    "my-speaker", sample_rate=16000, channels=1)
camera = Daily.create_camera_device(
    "my-camera",
    width=CAMERA_WIDTH,
    height=CAMERA_HEIGHT,
    color_format="RGB")

Daily.select_speaker_device("my-speaker")

client = CallClient()
meetting="https://autoark.daily.co/XXXXX"
print()
# print(f"Joining {"https://autoark.daily.co/XXXX"} ...")

client.join(meetting, client_settings={
    "inputs": {
        "camera": {
            "isEnabled": True,
            "settings": {
                "deviceId": "my-camera"
            }
        },
        "microphone": False
    }
})
client.leave()
client.release()

##and the error 
{"timestamp":"2024-07-19T06:19:04.006385Z","level":"ERROR","fields":{"message":"Failed to fetch room information: GET failed: Transport(Transport { kind: ConnectionFailed, message: Some(\"Connect error\"), url: Some(Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"gs.daily.co\")), port: None, path: \"/rooms/check/autoark/1r4by424NvuhJS8hOpRF\", query: None, fragment: None }), source: Some(Error { kind: TimedOut, message: \"connection timed out\" }) })"},"target":"daily_core::call_client"}
{"timestamp":"2024-07-19T06:19:04.006411Z","level":"ERROR","fields":{"message":"Failed to fetch room information: GET failed: Transport(Transport { kind: ConnectionFailed, message: Some(\"Connect error\"), url: Some(Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"gs.daily.co\")), port: None, path: \"/rooms/check/autoark/1r4by424NvuhJS8hOpRF\", query: None, fragment: None }), source: Some(Error { kind: TimedOut, message: \"connection timed out\" }) })"},"target":"daily_core::event"}
{"timestamp":"2024-07-19T06:19:04.007353Z","level":"ERROR","fields":{"message":"join (request 0) encountered an error: Connection(Api(RoomLookup(RoomInfoFetchFailed(Get(Transport(Transport { kind: ConnectionFailed, message: Some(\"Connect error\"), url: Some(Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"gs.daily.co\")), port: None, path: \"/rooms/check/autoark/1r4by424NvuhJS8hOpRF\", query: None, fragment: None }), source: Some(Error { kind: TimedOut, message: \"connection timed out\" }) }))))))"},"target":"daily_core::native::ffi::call_client"}

##envrionment 
a clound server

**Comment by aconchillo** [comment]
Hi @linyubupa ! That looks like a network issue. Are you still running into this issue?

**Comment by aconchillo** [comment]
I'll be closing this since this seemed a temporary network issue. Please, feel free to re-open if you run into it again.
