### ISSUE TITLE
can not install daliy-python

### ISSUE THREAD

**Issue by ouyangshaoxia** [daily-co/daily-python#24]
when I install daily-python
pip3 install daily-python

ERROR: Could not find a version that satisfies the requirement daily-python (from versions: none)
ERROR: No matching distribution found for daily-python

Can You Help Me

**Comment by kuzma2022** [comment]
same error

**Comment by aconchillo** [comment]
See #7

**Comment by ouyangshaoxia** [comment]
os : ubuntu18.04， python==3.10,
Could not find a version that satisfies the requirement daily-python

**Comment by ouyangshaoxia** [comment]
Can you provide the installation package in .whl format?

**Comment by kuzma2022** [comment]
My dear I received your email, what do you want me to do for you?🥰🥰🥰

**Comment by mlxu995** [comment]
same error on "CentOS Linux 7 (Core)"

**Comment by kuzma2022** [comment]
My dear, I can't see your message🥹🥹🥹

**Comment by munoz-romero** [comment]
I'm experiencing the same issue. Unable to install the package on:

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.102.1.el7.x86_64
Architecture: x86-64

**Comment by aconchillo** [comment]
> I'm experiencing the same issue. Unable to install the package on:
> 
> Operating System: CentOS Linux 7 (Core) Kernel: Linux 3.10.0-1160.102.1.el7.x86_64 Architecture: x86-64

Yep, same problem. CentOS 7 has a very old glibc (2.17, released in 2012) and it's actually already EOL. Unfortunately, CentOS 8 also has an old glibc.

**Comment by aconchillo** [comment]
Closing as duplicate of #7
