### ISSUE TITLE
Error joining  due to CreateSendTransportFailed when use pipecat

### ISSUE THREAD

**Issue by linyubupa** [daily-co/daily-python#26]
caught exception from libmediasoup: [json.exception.type_error.302] type must be array, but is string
{"timestamp":"2024-09-24T16:14:11.477790Z","level":"ERROR","fields":{"message":"Failed to create send transport: MediaSoupClientError(CreateSendTransportFailed)"},"target":"daily_core::call_manager::events::publishing::create_send_transport_handle_response"}
{"timestamp":"2024-09-24T16:14:11.477871Z","level":"ERROR","fields":{"message":"Mediasoup manager error: MediaSoup client error: Failed to create send transport"},"target":"daily_core::call_client"}
{"timestamp":"2024-09-24T16:14:11.477902Z","level":"ERROR","fields":{"message":"Mediasoup manager error: MediaSoup client error: Failed to create send transport"},"target":"daily_core::event"}
{"timestamp":"2024-09-24T16:14:11.478633Z","level":"ERROR","fields":{"message":"join (request 2) encountered an error: Subscription(MediasoupManagerError(MediaSoupClientError(CreateSendTransportFailed)))"},"target":"daily_core::native::ffi::call_client"}
2024-09-24 16:14:11.478 | ERROR    | pipecat.transports.services.daily:join:276 - Error joining https://autoark.daily.co/1r4by424NvuhJS8hOpRF: Subscription(MediasoupManagerError(MediaSoupClientError(CreateSendTransportFailed)))
{"timestamp":"2024-09-24T16:14:11.479074Z","level":"ERROR","fields":{"message":"sendAppMessage (request 3) encountered an error: AppMessage(Signalling(MessageSendFailed(TrySendError { kind: Disconnected })))"},"target":"daily_core::native::ffi::call_client"}

**Comment by aconchillo** [comment]
Closing. A bunch of things have been improved (specially on connection/reconnection), please try with a newer version and feel free to reopen if you still have issues.
