### ISSUE TITLE
Any plans on adding Windows distribution builds on PyPi ?

### ISSUE THREAD

**Issue by ttamoud** [daily-co/daily-python#28]

**Comment by aconchillo** [comment]
Yes, very soon! In the next few weeks.

**Comment by ttamoud** [comment]
Looking forward to that, you're making some amazing things over there at daily, thank u daily team ❤️

**Comment by Hades32** [comment]
great! Is there a pre-release for us to test?

**Comment by SarunasDev** [comment]
> Yes, very soon! In the next few weeks.

Hi, a month passed, any news?

**Comment by ttamoud** [comment]
It's a bummer, so many interesting projects and examples in pipecat-ai, yet unusable for most of us since we're on windows.

I've been working with wsl but its just not great, had to stop all my cooking for a while now, any news guys pl ? starting to lose hope over here

**Comment by Hades32** [comment]
dupe of https://github.com/daily-co/daily-python/issues/7

**Comment by aconchillo** [comment]
Closing. As already mentioned, duplicated from #7. Things have been a bit hectic, but I do definitely have plans to finish Windows support. It's half way there, from the same base Rust code I was able to get a working Windows build for https://github.com/daily-co/daily-core-sdk. So, it will happen for sure. It's actually a priority for the beginning of 2025.
