### ISSUE TITLE
pip install daily-python throws an error, is it a local issue or is anyone else facing the same?

### ISSUE THREAD

**Issue by adv-11** [daily-co/daily-python#32]
pip install daily-python
ERROR: Could not find a version that satisfies the requirement daily-python (from versions: none)
ERROR: No matching distribution found for daily-python

**Comment by adv-11** [comment]
![image](https://github.com/user-attachments/assets/5223b504-34e7-42bd-962f-84330b0f883d)

Problem with installing even basic objects like CallClient() or Daily() 

Any ideas on how to fix?

**Comment by aconchillo** [comment]
What platform are you using?

**Comment by adv-11** [comment]
Hi @aconchillo , just got a message from one of their devs, that it is LINUX only, 
They are planning to roll out windows in Q1 of 2025. 

Can close the issue, Thanks!

**Comment by aconchillo** [comment]
> Hi @aconchillo , just got a message from one of their devs, that it is LINUX only, They are planning to roll out windows in Q1 of 2025.
> 
> Can close the issue, Thanks!

Linux and macOS are fully supported. Windows is coming on Q1.
