### ISSUE TITLE
How to host multiple conversations?

### ISSUE THREAD

**Issue by nikhilro** [daily-co/daily-python#6]
Hey there, I need to create a server that can support many conversations happening concurrently. I saw a warning in https://docs.daily.co/guides/products/ai-toolkit#multiple-microphone-devices regarding creating different microphones. What would you suggest for multi-bot usecase?

For context, making an API for making voice assistants and trying to use Daily.co to deliver these assistants on web.

**Comment by RevanthRameshkumar** [comment]
Any answers for this? I have the same question here. @aconchillo?
